name: Scheduled Merge Remote Action
on: 
  schedule:
    - cron: '0 0 * * *'
    # scheduled for 00:00 every day
  push:
    branches: [ main ]

jobs:
  auto_compile:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Select Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: '3.7' # Version range or exact version of a Python version to use, using semvers version range syntax.
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - name: Install PlatformIO
        run: |
          pip install -U https://github.com/platformio/platformio-core/archive/develop.zip
          platformio update
      - name: Prepare for Compile
        run: |
          sudo apt-get install zsh
          ./compile_base.sh 
          echo "time_tag=v$(date +'%Y%m%d.%H%M%S')" >> $GITHUB_ENV                   
      - name: Compile Jyers Templates
        run: |
          ./compile_templates.sh                   
      - name: Upload bin files to GitHub releases
        uses: ncipollo/release-action@v1
        with:
          draft: false
          prerelease: true
          allowUpdates: true
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: ${{ env.SHORT_GITHUB_REF }}
          body: "These are auto builds of [Jyers Ender3 V2 work](https://github.com/Jyers/Marlin/tree/Ender_3_V2_Rewrite). Building is performed every day at midnight and no guarantee is given on if they actually work!"
          tag: JyersProfiles
          artifacts: "builds/*.bin"
          
